os: osx
language: c

addons:
  homebrew:
    taps: coslyk/mpv
    update: true


cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_cache:
  - brew cleanup

  
before_install:
  # Uninstall all existing packages to avoid conflicts
  - brew remove --force $(brew list) --ignore-dependencies

install:
  # Install dependencies
  - brew install nasm pkg-config texi2html aom fontconfig freetype gnutls lame libass libsoxr snappy speex x264 x265 xvid xz jpeg little-cms2

script:
  # Compile ffmpeg
  - brew install -v --build-bottle ffmpeg-lite
  # Compile mpv
  - brew install -v --build-bottle mpv-lite
  # Build bottles
  - brew bottle ffmpeg-lite
  - brew bottle mpv-lite


# Upload bottles
after_success:
  - curl -Lo upload.sh https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh *.tar.gz

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/
