os: osx
language: c

jobs:
  include:
    - name: macOS 10.14
      os: osx
      osx_image: xcode11.3
    
    - name: macOS 10.15
      os: osx
      osx_image: xcode12.2

addons:
  homebrew:
    taps: coslyk/mpv
    update: true

  
before_install:
  # Uninstall all existing packages to avoid conflicts
  - brew remove --force $(brew list) --ignore-dependencies

install:
  # Install dependencies
  - brew install nasm pkg-config python@3.9 fontconfig freetype gnutls libass libsoxr snappy speex xz jpeg little-cms2

script:
  # Compile ffmpeg
  - brew install -v --build-bottle ffmpeg-moonplayer
  # Compile mpv
  - brew install -v --build-bottle mpv-moonplayer
  # Build bottles
  - brew bottle ffmpeg-moonplayer
  - brew bottle mpv-moonplayer


# Upload bottles
after_success:
  - curl -Lo upload.sh https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh *.tar.gz

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/
