
name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14]

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install dependencies
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: |-
          brew tap coslyk/mpv
          brew developer on
          brew update
          brew install nasm pkg-config fontconfig freetype gnutls libass libsoxr snappy speex xz jpeg-turbo little-cms2 docutils meson ninja libplacebo

      - name: Install lld
        if: matrix.os == 'macos-13'
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: |-
          find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete
          brew install lld
          
      - name: Build packages
        run: |-
          brew install -v --build-bottle ffmpeg-moonplayer
          brew install -v --build-bottle mpv-moonplayer

      - name: Build bottles
        run: |-
          brew bottle ffmpeg-moonplayer
          brew bottle mpv-moonplayer

      - name: Upload bottles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          curl -Lo upload.sh https://github.com/probonopd/uploadtool/raw/master/upload.sh
          bash upload.sh *.tar.gz