
name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-15-intel]

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install dependencies
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: |-
          brew tap coslyk/mpv
          brew developer on
          brew update
          brew install nasm pkg-config fontconfig freetype gnutls libass libsoxr snappy speex xz jpeg-turbo little-cms2 docutils meson ninja libplacebo harfbuzz
          
      - name: Build packages
        run: |-
          brew install -v --build-bottle ffmpeg-moonplayer
          brew install -v --build-bottle mpv-moonplayer

      - name: Build bottles
        run: |-
          brew bottle ffmpeg-moonplayer
          brew bottle mpv-moonplayer

      - name: Upload bottles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv ffmpeg-moonplayer--*.bottle.1.tar.gz `ls ffmpeg-moonplayer--*.bottle.1.tar.gz | sed 's/--/-/g'`
          mv mpv-moonplayer--*.bottle.1.tar.gz `ls mpv-moonplayer--*.bottle.1.tar.gz | sed 's/--/-/g'`
          set -e
          curl -Lo upload.sh https://github.com/probonopd/uploadtool/raw/master/upload.sh
          bash upload.sh *.tar.gz