
name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-10.15]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: |-
          brew tap coslyk/mpv
          brew update
          brew install nasm pkg-config python@3.9 fontconfig freetype gnutls libass libsoxr snappy speex xz jpeg little-cms2

      - name: Build packages
        run: |-
          brew install -v --build-bottle ffmpeg-moonplayer
          brew install -v --build-bottle mpv-moonplayer

      - name: Build bottles
        run: |-
          brew bottle ffmpeg-moonplayer
          brew bottle mpv-moonplayer

      - name: Upload bottles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          curl -Lo upload.sh https://github.com/probonopd/uploadtool/raw/master/upload.sh
          bash upload.sh *.tar.gz